# Generated by Django 3.2.5 on 2021-07-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbs_down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbs_up',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
