# Generated by Django 3.2.5 on 2021-07-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210721_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descrption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
